### ISSUE TITLE
No "Level Name" in GM_ Object

### ISSUE THREAD

**Issue by RoqueNE** [powback/Bad-Company-2-Map-Editor#45]
There is only "Map Name". And it does nothing. Changed it to mp_001CQ and pressed the load button. but scene stay empty. http://prnt.sc/b1od19

**Comment by Powback** [comment]
Did you extract and convert the BC2 files?

**Comment by RoqueNE** [comment]
Yep. Have all the XML files.

Edit:
Btw, i have many .resdeleted files. Is that a problem?

**Comment by Powback** [comment]
That's fine. They can be deleted if you want.

The files have to be placed in a folder called Resources that should be placed in the root folder next to the project files. Should be next to Assets and Tools IIRC.

The Resources folder should contain Levels, Objects and a whole lot of other files.

Are you getting any errors in the console?

**Comment by Powback** [comment]
Also, everything looks correct in the screenshot. Did you press play?

**Comment by RoqueNE** [comment]
Yep. Have the folder "Bad-Company-2-Map-Editor-master" and in it Assets, Extractor, Library, Project Settings and Resources. In Resources folder i have still the normal game files (.exe and stuff) and the extracted and converted files. For Example in \Bad-Company-2-Map-Editor-master\Resources\Dist\win32\levels\mp_001\level-00 FbRB\levels : http://prntscr.com/b1oxl1

And yea, i pressed play and waited a moment. But there is nothing showing up in the Scene Tab. I can move the cam around, but there is just empty space.

Maybe something messed up while extracting / converting. Will try again.

**Comment by Powback** [comment]
Ah yes, that's the problem.

The folder structure should look like this: 
Bad-Company-2-Map-Editor-master\Resources\ and Animations, awards, Characters, Decals, Effects, Levels, etc. should be here.

I think you can solve your problem simply by placing everything from Win32 into Resources directly.

**Comment by RoqueNE** [comment]
Aah okay. Will try this. Take some time to copy everything. Will report back. Thanks!

That did the Trick. Thanks!
